export const ADD_GLOBAL_DATA = 'ADD_GLOBAL_DATA';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const LOAD_METRO = 'LOAD_METRO';

export const LOAD_TABLE_DATA = 'LOAD_TABLE_DATA';
export const LOAD_PAGE_TABLE_DATA = 'LOAD_PAGE_TABLE_DATA';
export const CHANGE_VACANCIES_PAGE = 'CHANGE_VACANCIES_PAGE';

export const LOAD_MAP_DATA = 'LOAD_MAP_DATA';
export const CHANGE_YMAP_STATE = 'CHANGE_YMAP_STATE';

export const LOAD_VACANCY = 'LOAD_VACANCY';

export const CHANGE_SELECTION = 'CHANGE_SELECTION';
export const CHANGE_SEARCHTEXT = 'CHANGE_SEARCHTEXT';

export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';
